int add_D51_coach(int x, char *c[]);
int add_D51_coach_r(int x);
int add_sl(int x, char *c[]);
int add_man(int x, int y);
int add_smoke(int x, int y);
int add_smoke_r(int x, int y);
int add_cross(int p);
int begin_gate(int p);
int end_gate(int p);
int x_gate(int p);
void end_proc();